on:
  release:
    types: [created]

jobs:
  release:
    name: release-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows
            archive: zip
            file_ext: ".exe"
          - os: ubuntu-latest
            name: linux
            archive: zip
            file_ext: ""
          - os: macos-latest
            name: mac
            archive: zip
            file_ext: ""
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0

      - name: Install System Libraries
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-dev libappindicator3-dev
          sudo apt-get install libxcb-xfixes0-dev
          sudo apt-get install libxcb-shape0-dev

      - name: Compile
        run: | 
          cargo build --release
          ls target/release

      - name: Package (Zip)
        run: |
          cd zipper && npm i && cd ..
          npx ts-node zipper/index deadliner.${{ matrix.archive }} @root/target/release/port.txt @root/target/release/deadliner${{ matrix.file_ext }} @root/target/release/deadliner-schedular${{ matrix.file_ext }} target/release/icons target/release/assets

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deadliner.${{ matrix.archive }}
          asset_name: deadliner-${{ matrix.name }}.${{ matrix.archive }}
          tag: ${{ github.ref }}
          overwrite: true
          body: ""
